baseurl = "http://golangph.com"
DefaultContentLanguage = "en"

title = "Golang Philippines"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[Params]
    author = "Golang Philippines"
    description = ""
    githubUsername = "golangph"
    accent = "#375EAB" # color
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
#  name = "Some Person"
#  website = "yourwebsite.com"

  facebook = "username"
  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "username"

  twitter = "username"

  instagram = "username"
  youtube = "user/username" # or channel/channelname


[[menu.main]]
    name = "About"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2

[[menu.main]]
    name = "Events"
    url = "/events"
    weight = 3

# For creating subtree in menu
# 
# [[menu.main]]
#     identifier = "samples"
#     name = "Samples"
#     weight = 3
# [[menu.main]]
#     parent = "samples"
#     name = "Big Image Sample"
#     url = "post/2017-03-07-bigimg-sample"
#     weight = 1
# 
# [[menu.main]]
#     parent = "samples"
#     name = "Math Sample"
#     url = "post/2017-03-05-math-sample"
#     weight = 2
# 
# [[menu.main]]
#     parent = "samples"
#     name = "Code Sample"
#     url = "post/2016-03-08-code-sample"
#     weight = 3
# 
# [[menu.main]]
#     name = "Tags"
#     url = "tags"
#     weight = 3
# 
  